//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_admin_message_trn
    {
        public int MessageTrnID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> RecipientID { get; set; }
        public System.DateTime SentTime { get; set; }
        public Nullable<bool> IsMessageViewed { get; set; }
        public System.DateTime MessageViewedTime { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public System.DateTime LastEdited { get; set; }
        public string Status { get; set; }
    
        public virtual in_user_mst in_user_mst { get; set; }
    }
}
