//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_admin_message_mst
    {
        public int MessageID { get; set; }
        public string Subject { get; set; }
        public string MessageText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
