//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_advertisement_mst
    {
        public int AdvertisementID { get; set; }
        public Nullable<int> AttachmentId { get; set; }
        public int PageID { get; set; }
        public string ContentType { get; set; }
        public string Companie { get; set; }
        public string AdvertisementUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime AdStartDate { get; set; }
        public System.DateTime AdEndDate { get; set; }
        public string Status { get; set; }
    
        public virtual in_attachment_mst in_attachment_mst { get; set; }
        public virtual in_pages_mst in_pages_mst { get; set; }
    }
}
