//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_attachment_mst
    {
        public in_attachment_mst()
        {
            this.in_advertisement_mst = new HashSet<in_advertisement_mst>();
        }
    
        public int AttachmentId { get; set; }
        public string FolderNaame { get; set; }
        public string AttachmentPath { get; set; }
    
        public virtual ICollection<in_advertisement_mst> in_advertisement_mst { get; set; }
    }
}
