//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_album_mst
    {
        public in_album_mst()
        {
            this.in_photo_mst = new HashSet<in_photo_mst>();
        }
    
        public int albumID { get; set; }
        public string AlbumName { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<in_photo_mst> in_photo_mst { get; set; }
        public virtual in_user_mst in_user_mst { get; set; }
    }
}
