//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_adminuser_mst
    {
        public in_adminuser_mst()
        {
            this.in_admin_photo = new HashSet<in_admin_photo>();
            this.in_adminprivileges_mst = new HashSet<in_adminprivileges_mst>();
        }
    
        public int AdminID { get; set; }
        public string AdminName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
        public string AdminType { get; set; }
        public string EmailID { get; set; }
    
        public virtual ICollection<in_admin_photo> in_admin_photo { get; set; }
        public virtual ICollection<in_adminprivileges_mst> in_adminprivileges_mst { get; set; }
    }
}
