//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_criteria_mst
    {
        public in_criteria_mst()
        {
            this.in_criteriaoptions_trn = new HashSet<in_criteriaoptions_trn>();
        }
    
        public int criteriaid { get; set; }
        public string criterianame { get; set; }
        public Nullable<int> criteriatype { get; set; }
        public string status { get; set; }
        public System.DateTime timestamp { get; set; }
        public string optionquestion { get; set; }
        public string preferencequestion { get; set; }
        public string MismatchText { get; set; }
        public Nullable<bool> ShowMatch { get; set; }
        public Nullable<bool> includeallInpreference { get; set; }
        public string includeallInpreferencetext { get; set; }
    
        public virtual ICollection<in_criteriaoptions_trn> in_criteriaoptions_trn { get; set; }
    }
}
