//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_forumpost_trn
    {
        public int trnid { get; set; }
        public Nullable<int> adminid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string posttitle { get; set; }
        public string posttext { get; set; }
        public System.DateTime timestamp { get; set; }
        public string status { get; set; }
        public Nullable<int> parentpostid { get; set; }
    }
}
