//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_language_mst
    {
        public in_language_mst()
        {
            this.in_userlanguage_trn = new HashSet<in_userlanguage_trn>();
        }
    
        public int LanguageId { get; set; }
        public string LanguageName { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<in_userlanguage_trn> in_userlanguage_trn { get; set; }
    }
}
