//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_message_reply
    {
        public int ReplyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public Nullable<bool> IsReply { get; set; }
    }
}
