//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_message_trn
    {
        public int messageID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> RecipientID { get; set; }
        public string MessageText { get; set; }
        public System.DateTime SentTime { get; set; }
        public Nullable<bool> IsMessageViewed { get; set; }
        public Nullable<System.DateTime> MessageViewedTime { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public Nullable<bool> MessageDeletedBySender { get; set; }
        public Nullable<bool> MessageDeletedByRecipient { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsRejected { get; set; }
    
        public virtual in_user_mst in_user_mst { get; set; }
        public virtual in_user_mst in_user_mst1 { get; set; }
    }
}
