//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_options_trn
    {
        public in_options_trn()
        {
            this.in_userquestions_trn = new HashSet<in_userquestions_trn>();
        }
    
        public int optionID { get; set; }
        public string OptionText { get; set; }
        public string IsGenderSpecific { get; set; }
        public Nullable<int> questionID { get; set; }
    
        public virtual in_question_mst in_question_mst { get; set; }
        public virtual ICollection<in_userquestions_trn> in_userquestions_trn { get; set; }
    }
}
