//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_photo_mst
    {
        public in_photo_mst()
        {
            this.in_admin_photo = new HashSet<in_admin_photo>();
            this.in_comments_trn = new HashSet<in_comments_trn>();
        }
    
        public int photoID { get; set; }
        public Nullable<int> albumID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AttachmentId { get; set; }
        public Nullable<int> AbusiveId { get; set; }
        public Nullable<bool> IsDefaultUserPhoto { get; set; }
        public Nullable<bool> IsDefaultAlbumPhoto { get; set; }
        public string PhotoTitle { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> PhotoSize { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<in_admin_photo> in_admin_photo { get; set; }
        public virtual in_album_mst in_album_mst { get; set; }
        public virtual ICollection<in_comments_trn> in_comments_trn { get; set; }
        public virtual in_user_mst in_user_mst { get; set; }
    }
}
