//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_question_mst
    {
        public in_question_mst()
        {
            this.in_options_trn = new HashSet<in_options_trn>();
            this.in_questionrating_trn = new HashSet<in_questionrating_trn>();
            this.in_userquestions_trn = new HashSet<in_userquestions_trn>();
        }
    
        public int questionID { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public int OptionNoneType { get; set; }
        public int OptionAllType { get; set; }
        public int OptionAddType { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<in_options_trn> in_options_trn { get; set; }
        public virtual ICollection<in_questionrating_trn> in_questionrating_trn { get; set; }
        public virtual ICollection<in_userquestions_trn> in_userquestions_trn { get; set; }
    }
}
