//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_userprofile_trn
    {
        public int ProfileId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BodyTypeId { get; set; }
        public Nullable<int> DrinkId { get; set; }
        public Nullable<int> EduId { get; set; }
        public Nullable<int> EthnicityId { get; set; }
        public Nullable<int> DrugId { get; set; }
        public Nullable<int> HaveChildrenId { get; set; }
        public Nullable<int> HoroscopeId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> SmokeId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> OrientationId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> IncomeId { get; set; }
        public Nullable<int> Height { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastEdited { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsUserType { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<bool> IsVesibleToStraightPeople { get; set; }
        public string ReligionImportance { get; set; }
        public string HoroscopeImportance { get; set; }
    
        public virtual in_bodytype_mst in_bodytype_mst { get; set; }
        public virtual in_drink_mst in_drink_mst { get; set; }
        public virtual in_drug_mst in_drug_mst { get; set; }
        public virtual in_education_mst in_education_mst { get; set; }
        public virtual in_ethnicity_mst in_ethnicity_mst { get; set; }
        public virtual in_havechildren_mst in_havechildren_mst { get; set; }
        public virtual in_horoscope_mst in_horoscope_mst { get; set; }
        public virtual in_income_mst in_income_mst { get; set; }
        public virtual in_jobtype_mst in_jobtype_mst { get; set; }
        public virtual in_location_mst in_location_mst { get; set; }
        public virtual in_orientation_mst in_orientation_mst { get; set; }
        public virtual in_religion_mst in_religion_mst { get; set; }
        public virtual in_smoke_mst in_smoke_mst { get; set; }
        public virtual in_user_mst in_user_mst { get; set; }
    }
}
