//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_userlanguage_trn
    {
        public int trnId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Proficiency { get; set; }
        public string Status { get; set; }
    
        public virtual in_language_mst in_language_mst { get; set; }
        public virtual in_user_mst in_user_mst { get; set; }
    }
}
