//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_userlogin_trn
    {
        public int trnID { get; set; }
        public System.DateTime LoginTime { get; set; }
        public string Browser { get; set; }
        public string OS { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Referer { get; set; }
        public Nullable<int> UserID { get; set; }
        public string IPAddress { get; set; }
    
        public virtual in_user_mst in_user_mst { get; set; }
    }
}
