//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateLib.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_user_mst
    {
        public in_user_mst()
        {
            this.in_admin_message_trn = new HashSet<in_admin_message_trn>();
            this.in_album_mst = new HashSet<in_album_mst>();
            this.in_comments_trn = new HashSet<in_comments_trn>();
            this.in_message_trn = new HashSet<in_message_trn>();
            this.in_message_trn1 = new HashSet<in_message_trn>();
            this.in_photo_mst = new HashSet<in_photo_mst>();
            this.in_questionrating_trn = new HashSet<in_questionrating_trn>();
            this.in_userlogin_trn = new HashSet<in_userlogin_trn>();
            this.in_userprofilesave_trn = new HashSet<in_userprofilesave_trn>();
            this.in_userprofilesave_trn1 = new HashSet<in_userprofilesave_trn>();
            this.in_userprofile_trn = new HashSet<in_userprofile_trn>();
            this.in_userquestions_trn = new HashSet<in_userquestions_trn>();
            this.in_userprofileview_trn = new HashSet<in_userprofileview_trn>();
            this.in_userlanguage_trn = new HashSet<in_userlanguage_trn>();
            this.in_userprofileview_trn1 = new HashSet<in_userprofileview_trn>();
            this.in_video_mst = new HashSet<in_video_mst>();
        }
    
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<int> Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserAgeInYears { get; set; }
        public System.DateTime LastOnlineTime { get; set; }
    
        public virtual ICollection<in_admin_message_trn> in_admin_message_trn { get; set; }
        public virtual ICollection<in_album_mst> in_album_mst { get; set; }
        public virtual ICollection<in_comments_trn> in_comments_trn { get; set; }
        public virtual ICollection<in_message_trn> in_message_trn { get; set; }
        public virtual ICollection<in_message_trn> in_message_trn1 { get; set; }
        public virtual ICollection<in_photo_mst> in_photo_mst { get; set; }
        public virtual ICollection<in_questionrating_trn> in_questionrating_trn { get; set; }
        public virtual ICollection<in_userlogin_trn> in_userlogin_trn { get; set; }
        public virtual ICollection<in_userprofilesave_trn> in_userprofilesave_trn { get; set; }
        public virtual ICollection<in_userprofilesave_trn> in_userprofilesave_trn1 { get; set; }
        public virtual ICollection<in_userprofile_trn> in_userprofile_trn { get; set; }
        public virtual ICollection<in_userquestions_trn> in_userquestions_trn { get; set; }
        public virtual ICollection<in_userprofileview_trn> in_userprofileview_trn { get; set; }
        public virtual ICollection<in_userlanguage_trn> in_userlanguage_trn { get; set; }
        public virtual ICollection<in_userprofileview_trn> in_userprofileview_trn1 { get; set; }
        public virtual ICollection<in_video_mst> in_video_mst { get; set; }
    }
}
