//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntellidateUser.web {
    
    
    public partial class WebForm4 {
        
        /// <summary>
        /// uc_viewedprofiles2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntellidateUser.web.uc.uc_viewedprofiles uc_viewedprofiles2;
        
        /// <summary>
        /// uc_userprofile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntellidateUser.web.uc.uc_userprofile uc_userprofile;
        
        /// <summary>
        /// uc_percentagecircle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntellidateUser.web.uc.uc_percentagecircle uc_percentagecircle;
        
        /// <summary>
        /// uc_viewedprofiles1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntellidateUser.web.uc.uc_viewedprofiles uc_viewedprofiles1;
        
        /// <summary>
        /// uc_smallpercentagecircle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntellidateUser.web.uc.uc_smallpercentagecircle uc_smallpercentagecircle1;
        
        /// <summary>
        /// uc_viewedprofiles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntellidateUser.web.uc.uc_viewedprofiles uc_viewedprofiles;
    }
}
